# C++ 11

all: vector deque string map function

vector: vector.cpp
	g++ -std=c++11 -o vector vector.cpp

deque: deque.cpp
	g++ -std=c++11 -o deque deque.cpp
	
string: string.cpp
	g++ -std=c++11 -o string string.cpp
	
map: map.cpp
	g++ -std=c++11 -o map map.cpp
	
function: function.cpp
	g++ -std=c++11 -o function function.cpp